### ISSUE TITLE
Izohga olingan kodni aniqlashtirish yoki kerak bo‘lmasa o‘chirib tashlash.

### ISSUE THREAD

**Issue by abdulqodir18** [ccenter-uz/CRM-Mahalla#21]
https://github.com/ccenter-uz/CRM-Mahalla/blob/03b2ce1488124525b46336708f5d46695612804a/src/%40core/pages/Callcenter/Drafts/api/getExcel.ts#L7

Shu qatordan (7-41) keyin izohga olingan kodlarni aniqlashtirish yoki kerak bo'lmasa o'chirib tashlash kerak.

**Comment by Yuldashevmd** [comment]
done 

![image](https://github.com/user-attachments/assets/10260660-cfb8-48e5-8419-5916cae9c026)
