### ISSUE TITLE
Hammasini bildirish uchun "all" keyword-idan foydalanish.

### ISSUE THREAD

**Issue by abdulqodir18** [ccenter-uz/CRM-Mahalla#22]
https://github.com/ccenter-uz/CRM-Mahalla/blob/03b2ce1488124525b46336708f5d46695612804a/src/%40core/pages/Callcenter/Drafts/api/index.tsx#L8

Shu yerda berilgan "1000000" hammasini bildirish uchun bo'lsa "all" keyword-dan foydalanish kerak. Maqsad readable kod yozish.

**Comment by Yuldashevmd** [comment]
buni backdan all qabul qiladigan qilsa kegin all keyni yuvora olaman ungaca all ni ozgaruvchiga olib qoyaman all dgan 1000 ni qoyib turaman
