### ISSUE TITLE
UI-ga error-ni chiqarish

### ISSUE THREAD

**Issue by abdulqodir18** [ccenter-uz/CRM-Mahalla#23]
1:
https://github.com/ccenter-uz/CRM-Mahalla/blob/03b2ce1488124525b46336708f5d46695612804a/src/%40core/pages/Callcenter/Drafts/api/index.tsx#L14

2:
https://github.com/ccenter-uz/CRM-Mahalla/blob/03b2ce1488124525b46336708f5d46695612804a/src/%40core/pages/Callcenter/Drafts/api/getExcel.ts#L87

Error handle qilinganda uni console-ga emas UI qismigiga chiqarish kerak.

**Comment by Yuldashevmd** [comment]
UI ga error chiqarish uchun interseptor qilib qoyganman 

![image](https://github.com/user-attachments/assets/ab742027-296a-445d-9498-4f8c8b79ca24)

![image](https://github.com/user-attachments/assets/0c45e17a-0d33-46c0-88c8-ad21c386b717)
