### ISSUE TITLE
Takror yoziladigan qiymatlar enum/const qilib olinishi

### ISSUE THREAD

**Issue by abdulqodir18** [ccenter-uz/CRM-Mahalla#24]
1:
https://github.com/ccenter-uz/CRM-Mahalla/blob/03b2ce1488124525b46336708f5d46695612804a/src/%40core/pages/Callcenter/Drafts/api/index.tsx#L6

2:
https://github.com/ccenter-uz/CRM-Mahalla/blob/03b2ce1488124525b46336708f5d46695612804a/src/%40core/pages/Callcenter/Drafts/ui/index.tsx#L94

Shu ikki holatda ham bir xil: `page: 1, pageSize: 100000, search: "null"` qiymatlar ishlatilyapti. Shularni enum yoki const qilib bitta joydan olib ishlatadigan qilish kerak

**Comment by Yuldashevmd** [comment]
Done 

![image](https://github.com/user-attachments/assets/16c5a1c4-c994-4ec5-9140-60d05199ec45)
