### ISSUE TITLE
Мурожаат келиб тушадиган вақтини автоматик белгилаш

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-Mahalla#3]
![image](https://github.com/user-attachments/assets/c1927bfc-5714-41ab-b18c-a7b0d8265649)

**Comment by Yuldashevmd** [comment]
Tayyor 

backenddan income_date keyga avtomatik qoyib yuborib manga qaytarsa boldi 

![image](https://github.com/user-attachments/assets/fd652a8e-c929-4338-91f1-996ff0a1cc1b)
