### ISSUE TITLE
Мурожаат юборишда инпут киритиш ва ўзгартириш

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-Mahalla#7]
Ўзгарадигон инпутлар:

Қўшиладигон инпутлар:
![image](https://github.com/user-attachments/assets/9e0f6fe8-9576-430b-be5a-744f43e92d48)
![Безымянный](https://github.com/user-attachments/assets/2809519e-3b38-4917-bf82-9095a10d0f53)

**Comment by Yuldashevmd** [comment]
Tayyor 

backend uchun key: 
tugilgan uchun input: **applicant_birthday**

![Uploading image.png…]()
