### ISSUE TITLE
Вилоят номлари

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-Mahalla#9]
![image](https://github.com/user-attachments/assets/97f444f2-abb7-41a8-93a4-e0156d4e68c0)
Вилоят номлари бош харфда (барча жойдагилар)

**Comment by Yuldashevmd** [comment]
Tayyor

![image](https://github.com/user-attachments/assets/6fa4c141-4295-4507-884d-f3a58392daa0)
